# Generated by Django 2.2 on 2020-07-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0004_auto_20200714_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
