# Generated by Django 2.2 on 2020-08-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0006_stockhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='test_date',
            field=models.DateTimeField(null=True),
        ),
    ]
