# Generated by Django 2.2 on 2020-08-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmgt', '0007_stockhistory_test_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='test_date',
        ),
    ]
